#!/bin/sh

if [ "x$OMP_NUM_THREADS" = "x" ]; then
    CPUS=`/usr/sbin/psrinfo | grep on-line | wc -l`
    if [ "x$CPUS" = "x" -o $CPUS = 0 ]; then
        CPUS=1
    fi

    OMP_NUM_THREADS=$CPUS
    export OMP_NUM_THREADS
fi

# Do not dynamically control the number of threads
OMP_DYNAMIC=0
export OMP_DYNAMIC

exec /usr/bin/darktable-bin
