#!/bin/sh

if [ "x$OMP_NUM_THREADS" = "x" ]; then
	CPUS=`/usr/sbin/psrinfo | grep on-line | wc -l`
	if [ "x$CPUS" = "x" -o $CPUS = 0 ]; then
	        CPUS=1
	fi

	export OMP_NUM_THREADS=$CPUS
fi

# Do not dynamically control the number of threads
export OMP_DYNAMIC=0

exec /usr/bin/darktable-bin
